- name: Remove vim.tiny
  apt:
    name: vim-tiny
    state: absent

- name: Install vim full
  apt:
    name: vim

- name: Ensure Curl is installed for vimplug
  apt:
    name: curl

- name: Set vim as default
  become: false
  lineinfile:
    name: "~/{{ item }}"
    regexp: "export VISUAL="
    line: "export VISUAL=vim"
  with_items:
    - .profile
    - .bashrc

- name: Set vim as default editor
  become: false
  lineinfile:
    name: "~/{{ item }}"
    regexp: "export EDITOR="
    line: "export EDITOR=$VISUAL"
  with_items:
    - .profile
    - .bashrc
